title: Tim Dalton
description: If you are on Github, might as well have a Github "blog"
author:
  name: Your Name Here,
  email: youremailaddress@example.com,
  url: https://github.com/daltontf/daltontf.github.io